#
# Copyright (C) 2006-2012 Opersys inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Import('env')
import os

kweb_FILES = ['python/kweb_forms.py',
              'python/kweb_getstrings.py',
              'python/kweb_lib.py',
              'python/kweb_menu.py',
              'python/kweb_mp.py',
              'python/kweb_session.py']

for pf in kweb_FILES:
    env.Install(dir = env['PYTHONDIR'], target = pf)

